CREATE VIEW BOOKS_AND_READERS AS
SELECT
    RD.READER_ID, RD.FIRSTNAME, RD.LASTNAME,
    BK.TITLE, RT.RENT_DATE, RT.RETURN_DATE
FROM READERS RD, BOOKS BK, RENTS RT
WHERE RT.BOOK_ID = BK.BOOK_ID
  AND RT.READER_ID = RD.READER_ID
ORDER BY RT.RENT_DATE;

SELECT
    *
FROM
    BOOKS_AND_READERS;

SELECT
    *
FROM
    BOOKS_AND_READERS
WHERE
        RENT_DATE > DATE_SUB(CURDATE(), INTERVAL 5 DAY);

SHOW PROCESSLIST;

-- WLACZENIE MECHANIZUMU ZDARZEN
SET GLOBAL EVENT_SCHEDULER=ON;

-- PRZYKLADOWE ZDARZENIE
USE kodilla_course;

CREATE EVENT UPDATE_VIPS
    ON SCHEDULE EVERY 1 MINUTE
    DO CALL UpdateVipLevels();

SELECT * from READERS;

UPDATE READERS
SET VIP_LEVEL = 'Not Set';


-- USUWANIE ZDARZENIA
DROP EVENT UPDATE_VIPS;