-- TWORZENIE TABELI ZE STATYSTKAMI
CREATE TABLE STATS (
                       STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
                       STAT_DATE DATETIME NOT NULL,
                       STAT VARCHAR(20) NOT NULL,
                       VALUE INT(11) NOT NULL
);

-- TWORZENIE WIDOKU
CREATE VIEW BESTSELLERS_COUNT AS
SELECT
    COUNT(*) AS BESTSELLERS_COUNT
FROM
    BOOKS
WHERE
        BESTSELLER = 1;

-- WYKORZYSTANIE WIDOKU
SELECT
    *
FROM
    BESTSELLERS_COUNT;

-- DODANIE ZDARZENIE AKTUALIZUJACEGO BESTSELLERY I STATYSTKI
DELIMITER $$
CREATE EVENT BESTSELLERS_COUNT
    ON SCHEDULE
        EVERY 1 MINUTE
    DO
BEGIN
CALL UpdateBestsellers();
INSERT INTO STATS(STAT_DATE, STAT, VALUE)
VALUES (CURDATE(),'BESTSELLERS', (select BESTSELLERS_COUNT FROM BESTSELLERS_COUNT));
END $$

DELIMITER ;

-- SPRAWDZENIE TABELI STATS
SELECT
    *
FROM
    STATS;

-- SPRAWDZENIE LISTY PROCESOW
SHOW PROCESSLIST;
